version: '3.8'
services:
  db:
    image: postgres:15
    container_name: dating_app_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dating_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: dating_app_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
